export const mockRawEvents = [
            {
                "watching_count": null,
                "olson_path": "America/Denver",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "CO",
                "postal_code": null,
                "going_count": null,
                "all_day": "2",
                "latitude": "39.6478",
                "groups": null,
                "url": "http://denver.eventful.com/events/child-jazz-/E0-001-114220260-3?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-114220260-3",
                "privacy": "1",
                "city_name": "Englewood",
                "link_count": null,
                "longitude": "-104.987",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Colorado",
                "start_time": "2018-07-10 00:00:00",
                "tz_id": null,
                "description": null,
                "modified": "2018-06-07 08:57:51",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Child Jazz",
                "venue_address": "1 Depot Square",
                "geocode_type": "City Based GeoCodes",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-05-08 05:34:30",
                "venue_id": "V0-001-012359920-8",
                "tz_city": null,
                "stop_time": "2018-08-17 00:00:00",
                "venue_name": "The Performing Arts School - Theater",
                "venue_url": "http://denver.eventful.com/venues/the-performing-arts-school-theater-/V0-001-012359920-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            },
            {
                "watching_count": null,
                "olson_path": "America/Denver",
                "calendar_count": null,
                "comment_count": null,
                "region_abbr": "CO",
                "postal_code": "80439",
                "going_count": null,
                "all_day": "2",
                "latitude": "39.6205219",
                "groups": null,
                "url": "http://denver.eventful.com/events/jazz-dance-event-jazz-1-/E0-001-113541732-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
                "id": "E0-001-113541732-2",
                "privacy": "1",
                "city_name": "Evergreen",
                "link_count": null,
                "longitude": "-105.3309161",
                "country_name": "United States",
                "country_abbr": "USA",
                "region_name": "Colorado",
                "start_time": "2018-07-12 00:00:00",
                "tz_id": null,
                "description": null,
                "modified": "2018-06-07 14:47:49",
                "venue_display": "1",
                "tz_country": null,
                "performers": null,
                "title": "Jazz dance Event - Jazz 1",
                "venue_address": "5300 South Olive Road",
                "geocode_type": "EVDB Geocoder",
                "tz_olson_path": null,
                "recur_string": null,
                "calendars": null,
                "owner": "evdb",
                "going": null,
                "country_abbr2": "US",
                "image": null,
                "created": "2018-04-05 03:15:28",
                "venue_id": "V0-001-006213160-8",
                "tz_city": null,
                "stop_time": "2018-08-02 00:00:00",
                "venue_name": "Wulf Recreation Center",
                "venue_url": "http://denver.eventful.com/venues/wulf-recreation-center-/V0-001-006213160-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
            }
          ]
   